---
baseURL: "https://www.relg.uk/"
locale: "en-us"
title: "relg.uk"
theme: "PaperMod"
enableRobotsTXT: true
enableEmoji: true
enableInlineShortcodes: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: "Christian Kugler"
  defaultTheme: "auto"
  dateFormat: 2006-01-02
  homeInfoParams:
    Title: "Hi there 👋"
    Content: "OpenSourcerer 🧙🏻‍♂️ (FOSS) who loves chocolate"
  socialIcons:
    - name: "github"
      url: "https://github.com/syphdias"
    - name: "mastodon"
      url: "https://social.linux.pizza/@syphdias"
    - name: "RSS"
      url: "index.xml"
  editPost:
    URL: "https://github.com/syphdias/syphdias.github.io/edit/main/content"
    appendFilePath: true
    Text: "Suggest Changes"
  ShowReadingTime: true
  ShowFullTextinRSS: true
  env: production
  social:
    fediverse_creator: "@syphdias@social.linux.pizza"
  images:
    - og-image.png

menu:
  main:
    - identifier: search
      pre: <img alt="search" class="menu-icon" src="/magnifying-glass-solid.svg">
      name: search
      url: /search/
      weight: 10
    - identifier: archive
      pre: <img alt="archive" class="menu-icon" src="/box-archive-solid.svg">
      name: archive
      url: /archives/
      weight: 20
languages:
  en:
    weight: 1
    label: "English"
