---

baseURL: "https://www.relg.uk/"
languageCode: "en-us"
title: "relg.uk"
theme: "PaperMod"
enableRobotsTXT: false
enableEmoji: true
enableInlineShortcodes: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  defaultTheme: "auto"
  dateFormat: 2006-01-02
  homeInfoParams:
    Title: "Hi there 👋"
    Content: "OpenSourcerer 🧙 (FOSS) who loves chocolate"
  socialIcons:
    - name: "github"
      url: "https://github.com/syphdias"
    - name: "mastodon"
      url: "https://social.linux.pizza/@syphdias"
    - name: "RSS"
      url: "index.xml"
  editPost:
    URL: "https://github.com/syphdias/syphdias.github.io/edit/main/content"
    appendFilePath: true
    Text: "Suggest Changes"
  ShowReadingTime: true
  ShowFullTextinRSS: true
  env: production
  social:
    # FIXME: upstream this
    fediverse_creator: "@syphdias@social.linux.pizza"

menu:
  main:
    - identifier: search
      pre: >
        <img src="/magnifying-glass-solid.svg"
        alt="search"
        style="height: 1em;
               width: 1em;
               display: inline-block;
               margin-right: 0.3em;
               vertical-align: middle;">
      name: search
      url: /search/
      weight: 10
    - identifier: archive
      pre: >
        <img src="/box-archive-solid.svg"
        alt="archive"
        style="height: 1em;
               width: 1em;
               display: inline-block;
               margin-right: 0.3em;
               vertical-align: middle;">
      name: archive
      url: /archives/
      weight: 20
languages:
  en:
    weight: 1
    languageName: "English"
