name: Renovate
on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4 (tag) @ 34e114876b0b11c390a56381ad16ebd13914f8d5 (sha)
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Self-hosted Renovate
        # v46.1.13 (tag) @ 79dc0ba74dc3de28db0a7aeb1d0b95d5bf5fde2a (sha)
        uses: renovatebot/github-action@79dc0ba74dc3de28db0a7aeb1d0b95d5bf5fde2a
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}